name: Create Release Notes

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the current tag
        id: get_current_tag
        run: |
          echo "CURRENT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: List all tags
        id: list_tags
        run: |
          tags=$(git tag --sort=-creatordate)
          echo "TAGS=$tags" >> $GITHUB_ENV

      - name: Get the previous tag
        id: get_previous_tag
        run: |
          current_tag=${{ env.CURRENT_TAG }}
          previous_tag=$(echo "${{ env.TAGS }}" | grep -E '^v' | grep -v $current_tag | head -n 1)
          echo "Current tag: $current_tag"
          echo "Previous tag: $previous_tag"
          echo "PREVIOUS_TAG=$previous_tag" >> $GITHUB_ENV

      - name: Generate release notes
        id: generate_release_notes
        run: |
          previous_tag=${{ env.PREVIOUS_TAG }}
          current_tag=${{ env.CURRENT_TAG }}
          changes=$(git log $previous_tag..$current_tag --oneline)
          full_changelog=$(git log --oneline)
          echo "## Release Notes for $current_tag" > release_notes.md
          echo "Comparing $previous_tag...$current_tag" >> release_notes.md
          echo "## What's Changed" >> release_notes.md
          echo "$changes" >> release_notes.md
          echo "## Full Changelog" >> release_notes.md
          echo "$full_changelog" >> release_notes.md
          echo "## Tag List" >> release_notes.md
          echo "${{ env.TAGS }}" >> release_notes.md

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.CURRENT_TAG }}
          release_name: Release-${{ env.CURRENT_TAG }}
          body_path: ./release_notes.md
