name: Generate Release Notes

on:
  push:
    tags:
      - 'v*'

jobs:
  release-notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get previous tag
      id: prev-tag
      run: echo "PREV_TAG=$(git describe --tags --abbrev=0 HEAD^)" >> $GITHUB_ENV

    - name: Get current tag
      id: curr-tag
      run: echo "CURR_TAG=$(git describe --tags --abbrev=0 HEAD)" >> $GITHUB_ENV

    - name: Generate release notes
      id: release-notes
      run: |
        echo "## What's Changed" > release-notes.md
        for COMMIT_HASH in $(git log $PREV_TAG..$CURR_TAG --pretty=format:"%h"); do
          COMMIT_MESSAGE=$(git log -1 --pretty=%B $COMMIT_HASH | head -n 1)
          echo "- $COMMIT_HASH $COMMIT_MESSAGE" >> release-notes.md
        done

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release-${{ env.CURR_TAG }}
        generate_release_notes: true
        body_path: release-notes.md
        previous_tag_name: ${{ env.PREV_TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
